# Generated by Django 5.2.11 on 2026-03-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedvideo',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedvideo',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('wo', 'Wolof')], default='fr', max_length=10),
        ),
        migrations.AddField(
            model_name='generatedvideo',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
