# Generated by Django 5.2.11 on 2026-03-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_ai', '0002_generatedvideo_facebook_url_generatedvideo_language_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedvideo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vidéo générée', 'verbose_name_plural': 'Vidéos générées'},
        ),
        migrations.AddField(
            model_name='generatedvideo',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Durée en secondes', null=True),
        ),
        migrations.AddField(
            model_name='generatedvideo',
            name='status',
            field=models.CharField(choices=[('generated', 'Générée'), ('published', 'Publiée'), ('failed', 'Erreur')], default='generated', max_length=20),
        ),
        migrations.AddField(
            model_name='generatedvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', verbose_name='Miniature'),
        ),
        migrations.AddField(
            model_name='generatedvideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien Facebook'),
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('wo', 'Wolof')], default='fr', max_length=10, verbose_name='Langue'),
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='script',
            field=models.TextField(verbose_name='Script vidéo'),
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien TikTok'),
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='video_file',
            field=models.FileField(upload_to='videos/', verbose_name='Fichier vidéo'),
        ),
    ]
