# Generated by Django 5.2.11 on 2026-03-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_ai', '0003_alter_generatedvideo_options_generatedvideo_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedvideo',
            options={},
        ),
        migrations.RemoveField(
            model_name='generatedvideo',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='generatedvideo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='generatedvideo',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='generatedvideo',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('wo', 'Wolof')], default='fr', max_length=10),
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='script',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='video_file',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
