# Generated by Django 5.2.11 on 2026-03-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_ai', '0004_alter_generatedvideo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedvideo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vidéo générée', 'verbose_name_plural': 'Vidéos générées'},
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien Facebook'),
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('wo', 'Wolof')], default='fr', max_length=10, verbose_name='Langue'),
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='script',
            field=models.TextField(verbose_name='Script de la vidéo'),
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien TikTok'),
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre de la vidéo'),
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='video_file',
            field=models.FileField(max_length=500, upload_to='videos/', verbose_name='Fichier vidéo'),
        ),
    ]
