# Generated by Django 5.2.11 on 2026-04-04 13:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('group_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_reset', models.DateTimeField(blank=True, null=True)),
                ('code_invitation', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invitation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('montant_base', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('montant_fixe_gagnant', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('cycle_numero', models.IntegerField(default=1)),
                ('tour_actuel', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('cycle_termine', models.BooleanField(default=False)),
                ('tirage_effectue', models.BooleanField(default=False)),
                ('auto_reset', models.BooleanField(default=True)),
                ('autoriser_ajout_membre', models.BooleanField(default=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_administres_tontine', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='cotisationtontine.group')),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='cotisationtontine.group')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('montant', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('a_recu', models.BooleanField(default=False, help_text='Indique si ce membre a déjà reçu la cagnotte dans ce cycle')),
                ('ordre_passage', models.IntegerField(blank=True, help_text='Ordre de passage dans la tontine (optionnel)', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('exit_liste', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='cotisationtontine.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_ajout'],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='prochain_gagnant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_prochain_gagnant', to='cotisationtontine.groupmember'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='cotisationtontine.group')),
            ],
        ),
        migrations.CreateModel(
            name='Tirage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('cycle_number', models.PositiveIntegerField(default=1)),
                ('tour', models.PositiveIntegerField(default=1, help_text='Numéro du tour dans le cycle')),
                ('date_tirage', models.DateTimeField(auto_now_add=True)),
                ('gagnant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tirages_gagnes', to='cotisationtontine.groupmember')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tirages', to='cotisationtontine.group')),
            ],
            options={
                'ordering': ['-date_tirage'],
            },
        ),
        migrations.CreateModel(
            name='EtapeCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_etape', models.IntegerField()),
                ('date_etape', models.DateTimeField()),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='cotisationtontine.cycle')),
                ('tirage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotisationtontine.tirage')),
            ],
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.PositiveIntegerField(default=1, help_text='Numéro du tour de tontine')),
                ('cycle', models.PositiveIntegerField(default=1, help_text='Numéro du cycle')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('frais', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('methode', models.CharField(choices=[('WAVE', 'Wave'), ('OM', 'Orange Money'), ('CAISSE', 'Caisse')], default='WAVE', max_length=20)),
                ('preuve', models.ImageField(blank=True, null=True, upload_to='preuves/')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('note_admin', models.TextField(blank=True, help_text='Raison du refus ou commentaire', null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='cotisationtontine.groupmember')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements_valides_tontine', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='tirage',
            index=models.Index(fields=['group', 'cycle_number', 'tour'], name='cotisationt_group_i_66988b_idx'),
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['member', 'tour'], name='cotisationt_member__58522f_idx'),
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['member', 'cycle'], name='cotisationt_member__98c240_idx'),
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['statut'], name='cotisationt_statut_cc8646_idx'),
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['tour', 'cycle'], name='cotisationt_tour_d3497e_idx'),
        ),
    ]
