# Generated by Django 5.2.3 on 2025-08-05 22:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du groupe')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_reset', models.DateTimeField(blank=True, null=True)),
                ('code_invitation', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="Code d'invitation")),
                ('montant_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant de base')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_administres', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('exit_liste', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='cotisationtontine.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre du groupe',
                'verbose_name_plural': 'Membres du groupe',
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CotisationTontine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('VALIDE', 'Validé'), ('EN_ATTENTE', 'En attente'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='cotisationtontine.groupmember')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('RESET_CYCLE', 'Réinitialisation du cycle'), ('AUTRE', 'Autre action')], max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='cotisationtontine.group')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expire_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='cotisationtontine.group')),
            ],
        ),
        migrations.CreateModel(
            name='Tirage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tirage', models.DateField(auto_now_add=True, verbose_name='Date du tirage')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant du tirage')),
                ('gagnant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tirages_gagnes', to='cotisationtontine.groupmember', verbose_name='Membre gagnant')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tirages', to='cotisationtontine.group', verbose_name='Groupe')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tirages_participes', to='cotisationtontine.groupmember', verbose_name='Membre tiré')),
            ],
        ),
        migrations.CreateModel(
            name='TirageHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_tirage', models.DateTimeField(auto_now_add=True)),
                ('gagnant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotisationtontine.groupmember', verbose_name='Gagnant')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tirages_historiques', to='cotisationtontine.group')),
            ],
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant net du versement (hors frais).', max_digits=12)),
                ('frais', models.DecimalField(decimal_places=2, default=0, help_text='Frais appliqués sur le paiement.', max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('methode', models.CharField(choices=[('PAYDUNYA', 'PayDunya'), ('CASH', 'Caisse')], default='PAYDUNYA', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='cotisationtontine.groupmember')),
            ],
        ),
    ]
