# Generated by Django 5.2.3 on 2025-08-24 03:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'adhésion"),
        ),
    ]
