# Generated by Django 5.2.11 on 2026-03-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='tour_actuel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='auto_reset',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='cycle_termine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
