# Generated by Django 5.2.11 on 2026-04-05 03:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='versement',
            name='cotisationt_tour_d3497e_idx',
        ),
        migrations.AlterField(
            model_name='versement',
            name='cycle',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='versement',
            name='note_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='versement',
            name='preuve',
            field=models.ImageField(blank=True, null=True, upload_to='preuves/tontine/'),
        ),
        migrations.AlterField(
            model_name='versement',
            name='tour',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='versement',
            constraint=models.UniqueConstraint(condition=models.Q(('statut__in', ['EN_ATTENTE', 'VALIDE'])), fields=('member', 'cycle', 'tour'), name='unique_paiement_par_tour'),
        ),
    ]
