# Generated by Django 5.2.3 on 2025-08-07 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementGagnant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('SUCCES', 'Succès'), ('ECHEC', 'Échec')], max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('gagnant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_reçus', to='cotisationtontine.groupmember')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='cotisationtontine.group')),
            ],
            options={
                'verbose_name': 'Paiement gagnant',
                'verbose_name_plural': 'Paiements des gagnants',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
