# Generated by Django 5.2.3 on 2025-08-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
