# Generated by Django 5.2.11 on 2026-04-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='numero',
            field=models.IntegerField(default=1),
        ),
    ]
