# Generated by Django 5.2.11 on 2026-04-05 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0002_remove_versement_cotisationt_tour_d3497e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cotisationtontine.group'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='ordre_passage',
            field=models.PositiveIntegerField(blank=True, help_text='Ordre de passage dans la tontine (optionnel)', null=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group'], name='cotisationt_group_i_e2c48a_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['user'], name='cotisationt_user_id_27dbd8_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='unique_member_per_group'),
        ),
    ]
