# Generated by Django 5.2.11 on 2026-04-01 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0002_cycle_numero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='versement',
            name='cycle',
            field=models.IntegerField(default=1, help_text='Numéro du cycle'),
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['member', 'cycle'], name='cotisationt_member__98c240_idx'),
        ),
    ]
