# Generated by Django 5.2.3 on 2025-08-08 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0002_paiementgagnant'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='cotisationtontine.group'),
        ),
        migrations.AlterField(
            model_name='historiqueaction',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_actions', to='cotisationtontine.group'),
        ),
    ]
