# Generated by Django 5.2.3 on 2025-08-24 04:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0002_groupmember_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmember',
            options={},
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
