# Generated by Django 5.2.11 on 2026-03-30 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0002_group_tour_actuel_alter_group_auto_reset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='versement',
            name='tour',
            field=models.IntegerField(default=1, help_text='Numéro du tour de tontine'),
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['member', 'tour'], name='cotisationt_member__58522f_idx'),
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['statut'], name='cotisationt_statut_cc8646_idx'),
        ),
    ]
