# Generated by Django 5.2.3 on 2025-08-04 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0002_alter_tirage_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tirage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotisationtontine.group'),
        ),
    ]
