# Generated by Django 5.2.11 on 2026-04-05 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0003_alter_groupmember_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupmember',
            name='unique_member_per_group',
        ),
        migrations.RemoveConstraint(
            model_name='versement',
            name='unique_paiement_par_tour',
        ),
        migrations.RemoveIndex(
            model_name='groupmember',
            name='cotisationt_group_i_e2c48a_idx',
        ),
        migrations.RemoveIndex(
            model_name='groupmember',
            name='cotisationt_user_id_27dbd8_idx',
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='cotisationtontine.group'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='ordre_passage',
            field=models.IntegerField(blank=True, help_text='Ordre de passage dans la tontine (optionnel)', null=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='versement',
            name='cycle',
            field=models.PositiveIntegerField(default=1, help_text='Numéro du cycle'),
        ),
        migrations.AlterField(
            model_name='versement',
            name='note_admin',
            field=models.TextField(blank=True, help_text='Raison du refus ou commentaire', null=True),
        ),
        migrations.AlterField(
            model_name='versement',
            name='preuve',
            field=models.ImageField(blank=True, null=True, upload_to='preuves/'),
        ),
        migrations.AlterField(
            model_name='versement',
            name='tour',
            field=models.PositiveIntegerField(default=1, help_text='Numéro du tour de tontine'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['tour', 'cycle'], name='cotisationt_tour_d3497e_idx'),
        ),
    ]
