# Generated by Django 5.2.3 on 2025-08-04 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0003_alter_tirage_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tirage',
            name='date_tirage',
            field=models.DateField(auto_now_add=True, verbose_name='Date du tirage'),
        ),
        migrations.AlterField(
            model_name='tirage',
            name='gagnant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tirages_gagnes', to='cotisationtontine.groupmember', verbose_name='Membre gagnant'),
        ),
        migrations.AlterField(
            model_name='tirage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tirages', to='cotisationtontine.group', verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='tirage',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tirages_participes', to='cotisationtontine.groupmember', verbose_name='Membre tiré'),
        ),
        migrations.AlterField(
            model_name='tirage',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant du tirage'),
        ),
    ]
