# Generated by Django 5.2.11 on 2026-03-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0003_versement_tour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tirage',
            name='tour',
            field=models.PositiveIntegerField(default=1, help_text='Numéro du tour dans le cycle'),
        ),
        migrations.AlterField(
            model_name='group',
            name='autoriser_ajout_membre',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='montant_base',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='group',
            name='montant_fixe_gagnant',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddIndex(
            model_name='tirage',
            index=models.Index(fields=['group', 'cycle_number', 'tour'], name='cotisationt_group_i_66988b_idx'),
        ),
    ]
