# Generated by Django 5.2.3 on 2025-08-31 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0004_groupmember_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='expire_at',
        ),
    ]
