# Generated by Django 5.2.11 on 2026-03-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0004_tirage_tour_alter_group_autoriser_ajout_membre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='tirage_effectue',
            field=models.BooleanField(default=False),
        ),
    ]
