# Generated by Django 5.2.3 on 2025-08-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0004_alter_tirage_date_tirage_alter_tirage_gagnant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='date_reset',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière réinitialisation'),
        ),
    ]
