# Generated by Django 5.2.3 on 2025-08-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0004_group_prochain_gagnant'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='montant_fixe_gagnant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant fixe pour les gagnants'),
        ),
    ]
