# Generated by Django 5.2.3 on 2026-02-24 01:57

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0005_remove_invitation_expire_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiementgagnant',
            name='gagnant',
        ),
        migrations.RemoveField(
            model_name='paiementgagnant',
            name='group',
        ),
        migrations.RemoveField(
            model_name='tiragehistorique',
            name='gagnant',
        ),
        migrations.RemoveField(
            model_name='tiragehistorique',
            name='group',
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterModelOptions(
            name='versement',
            options={'ordering': ['-date_creation']},
        ),
        migrations.RenameField(
            model_name='versement',
            old_name='date',
            new_name='date_creation',
        ),
        migrations.RemoveField(
            model_name='tirage',
            name='membre',
        ),
        migrations.RemoveField(
            model_name='versement',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='versement',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='versement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='versement',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements_valides_tontine', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_administres_tontine', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='montant_base',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='group',
            name='montant_fixe_gagnant',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='prochain_gagnant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_prochain_gagnant', to='cotisationtontine.groupmember'),
        ),
        migrations.AlterField(
            model_name='group',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='montant',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tirage',
            name='date_tirage',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tirage',
            name='gagnant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tirages_gagnes', to='cotisationtontine.groupmember'),
        ),
        migrations.AlterField(
            model_name='tirage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tirages', to='cotisationtontine.group'),
        ),
        migrations.AlterField(
            model_name='tirage',
            name='montant',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='versement',
            name='frais',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='versement',
            name='methode',
            field=models.CharField(default='CAISSE', max_length=20),
        ),
        migrations.AlterField(
            model_name='versement',
            name='montant',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.DeleteModel(
            name='CotisationTontine',
        ),
        migrations.DeleteModel(
            name='PaiementGagnant',
        ),
        migrations.DeleteModel(
            name='TirageHistorique',
        ),
    ]
