# Generated by Django 5.2.3 on 2025-08-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0005_group_date_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='last_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
