# Generated by Django 5.2.3 on 2025-08-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0006_group_last_reset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='date_reset',
        ),
        migrations.AddField(
            model_name='group',
            name='date_dernier_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
