# Generated by Django 5.2.11 on 2026-02-26 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0006_remove_paiementgagnant_gagnant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tirage',
            options={'ordering': ['-date_tirage']},
        ),
        migrations.AddField(
            model_name='tirage',
            name='cycle_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tirage',
            name='date_tirage',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tirage',
            name='gagnant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotisationtontine.groupmember'),
        ),
    ]
