# Generated by Django 5.2.11 on 2026-02-26 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0007_alter_tirage_options_tirage_cycle_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tirage',
            name='gagnant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tirages_gagnes', to='cotisationtontine.groupmember'),
        ),
        migrations.DeleteModel(
            name='HistoriqueAction',
        ),
    ]
