# Generated by Django 5.2.3 on 2025-08-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0008_historiqueaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='date_dernier_reset',
            new_name='date_reset',
        ),
    ]
