# Generated by Django 5.2.11 on 2026-03-05 16:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(help_text='Numéro de téléphone au format international', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='numéro de téléphone')),
                ('nom', models.CharField(help_text='Votre nom complet', max_length=150, verbose_name='nom complet')),
                ('alias', models.CharField(blank=True, help_text='Nom alternatif ou alias (optionnel)', max_length=150, null=True, verbose_name='alias')),
                ('email', models.EmailField(blank=True, help_text='Adresse email (optionnelle)', max_length=254, null=True, verbose_name='adresse email')),
                ('option', models.CharField(choices=[('1', 'Cotisation & Tontine'), ('2', 'Épargne & Crédit')], default='1', help_text="Option choisie lors de l'inscription", max_length=1, verbose_name="Option d'inscription")),
                ('is_validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('terms_version', models.CharField(blank=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Désigne si cet utilisateur doit être traité comme actif.', verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, help_text='Autorise l’accès à l’administration Django.', verbose_name='membre du staff')),
                ('is_super_admin', models.BooleanField(default=False, help_text='Utilisateur avec tous les droits YaayESS.', verbose_name='super administrateur')),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', related_query_name='customuser', to='auth.group', verbose_name='groupes')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_permissions', related_query_name='customuser', to='auth.permission', verbose_name='permissions utilisateur')),
                ('validated_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['nom', 'phone'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
