# Generated by Django 5.2.3 on 2025-08-24 02:29

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['nom', 'phone'], 'verbose_name': 'utilisateur', 'verbose_name_plural': 'utilisateurs'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="date d'inscription"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, help_text='Adresse email (optionnelle)', max_length=254, null=True, verbose_name='adresse email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Les groupes auxquels appartient cet utilisateur. Un utilisateur obtiendra toutes les permissions accordées à chacun de ses groupes.', related_name='customuser_groups', related_query_name='customuser', to='auth.group', verbose_name='groupes'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Désigne si cet utilisateur doit être traité comme actif.', verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text="Désigne si l'utilisateur peut se connecter à l'interface d'administration.", verbose_name='membre du staff'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_super_admin',
            field=models.BooleanField(default=False, help_text="Désigne si l'utilisateur a tous les droits sans limitation.", verbose_name='super administrateur'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nom',
            field=models.CharField(help_text='Votre nom complet', max_length=150, verbose_name='nom complet'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(help_text='Numéro de téléphone au format international', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions spécifiques pour cet utilisateur.', related_name='customuser_permissions', related_query_name='customuser', to='auth.permission', verbose_name='permissions utilisateur'),
        ),
    ]
