# Generated by Django 5.2.3 on 2025-08-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groupes auxquels appartient cet utilisateur.', related_name='customuser_set', to='auth.group', verbose_name='groupes'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions spécifiques pour cet utilisateur.', related_name='customuser_set', to='auth.permission', verbose_name='permissions utilisateur'),
        ),
    ]
