# Generated by Django 5.2.11 on 2026-03-08 05:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='abonnement_actif',
            field=models.BooleanField(default=True, help_text="Accès autorisé à l'application"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_activation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(help_text='Numéro de téléphone au format international', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='numéro de téléphone'),
        ),
    ]
