# Generated by Django 5.2.11 on 2026-04-04 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('epargnecredit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='epargnecredit.group'),
        ),
        migrations.AddField(
            model_name='member',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.group'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otpattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otpattempt',
            name='otp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.otpverification'),
        ),
        migrations.AddField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member'),
        ),
        migrations.AddField(
            model_name='versement',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='accounts.member'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone'], name='accounts_cu_phone_c30b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['nom'], name='accounts_cu_nom_1eaf4c_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['abonnement_actif'], name='accounts_cu_abonnem_74d20e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['date_expiration'], name='accounts_cu_date_ex_5e374b_idx'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('phone',), name='unique_phone_user'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['admin'], name='accounts_gr_admin_i_eaa5f5_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['is_active'], name='accounts_gr_is_acti_69d112_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['code'], name='accounts_in_code_46fcb0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('group', 'mois')},
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['group'], name='accounts_me_group_i_3088ea_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['user'], name='accounts_me_user_id_7cf4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['group', 'user'], name='accounts_me_group_i_24798b_idx'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='unique_member_group'),
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['member'], name='accounts_ve_member__df941f_idx'),
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['created_at'], name='accounts_ve_created_2c15c9_idx'),
        ),
    ]
