# Generated by Django 5.2.3 on 2025-08-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='alias',
            field=models.CharField(blank=True, help_text='Nom alternatif ou alias (optionnel)', max_length=150, null=True, verbose_name='alias'),
        ),
    ]
