# Generated by Django 5.2.11 on 2026-03-08 16:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_abonnement_actif_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['nom'], 'verbose_name': 'utilisateur', 'verbose_name_plural': 'utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='abonnement_actif',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='alias'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_expiration',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='adresse email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='yaayess_users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Autorise l’accès à l’administration Django.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_super_admin',
            field=models.BooleanField(default=False, help_text='Utilisateur avec tous les droits YaayESS.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nom',
            field=models.CharField(db_index=True, max_length=150, verbose_name='nom complet'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='option',
            field=models.CharField(choices=[('1', 'Cotisation & Tontine'), ('2', 'Épargne & Crédit')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(db_index=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro doit être au format '+999999999'. Maximum 15 chiffres.", regex='^\\+?1?\\d{9,15}$')], verbose_name='numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='terms_version',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='yaayess_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invited_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone'], name='accounts_cu_phone_c30b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['nom'], name='accounts_cu_nom_1eaf4c_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['abonnement_actif'], name='accounts_cu_abonnem_74d20e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['date_expiration'], name='accounts_cu_date_ex_5e374b_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['code'], name='accounts_in_code_46fcb0_idx'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('phone',), name='unique_phone_user'),
        ),
    ]
