# Generated by Django 5.2.3 on 2025-08-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='option',
            field=models.CharField(blank=True, choices=[('1', 'Cotisation & Tontine'), ('2', 'Epargne & Crédit')], help_text="Choix de l'option lors de l'inscription", max_length=1, null=True, verbose_name="option d'inscription"),
        ),
    ]
