# Generated by Django 5.2.11 on 2026-04-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='max_attempts',
            field=models.IntegerField(default=3),
        ),
    ]
