# Generated by Django 5.2.11 on 2026-03-08 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_alter_invitation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('montant_base', models.PositiveIntegerField()),
                ('members_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField()),
                ('commission', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='accounts.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['admin'], name='accounts_gr_admin_i_eaa5f5_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['is_active'], name='accounts_gr_is_acti_69d112_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['group'], name='accounts_me_group_i_3088ea_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['user'], name='accounts_me_user_id_7cf4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['group', 'user'], name='accounts_me_group_i_24798b_idx'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='unique_member_group'),
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['member'], name='accounts_ve_member__df941f_idx'),
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['created_at'], name='accounts_ve_created_2c15c9_idx'),
        ),
    ]
