# Generated by Django 5.2.11 on 2026-04-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otpverification_attempts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpattempt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='otpattempt',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='otpattempt',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
