# Generated by Django 5.2.11 on 2026-03-10 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_group_member_versement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versement',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='versement',
            name='accounts_ve_member__df941f_idx',
        ),
        migrations.RemoveIndex(
            model_name='versement',
            name='accounts_ve_created_2c15c9_idx',
        ),
        migrations.RenameField(
            model_name='versement',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='versement',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='versement',
            name='total',
        ),
        migrations.AddField(
            model_name='versement',
            name='frais_plateforme',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='versement',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member'),
        ),
        migrations.AlterField(
            model_name='versement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
