# Generated by Django 5.2.3 on 2025-09-01 04:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'inscription"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='option',
            field=models.CharField(choices=[('1', 'Cotisation & Tontine'), ('2', 'Épargne & Crédit')], default='1', help_text="Option choisie lors de l'inscription", max_length=1, verbose_name="Option d'inscription"),
        ),
    ]
