# Generated by Django 5.2.11 on 2026-04-02 05:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otpattempt_options_otpattempt_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=accounts.models.OTPVerification.default_expiry),
        ),
    ]
