# Generated by Django 5.2.11 on 2026-03-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_versement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pays',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='pays'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ville',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ville'),
        ),
    ]
