# Generated by Django 5.2.11 on 2026-03-12 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_pays_customuser_ville'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versement',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='versement',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='versement',
            name='frais_plateforme',
        ),
        migrations.AddField(
            model_name='versement',
            name='commission',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='versement',
            name='total',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='versement',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='accounts.member'),
        ),
        migrations.AlterField(
            model_name='versement',
            name='montant',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['member'], name='accounts_ve_member__df941f_idx'),
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['created_at'], name='accounts_ve_created_2c15c9_idx'),
        ),
    ]
