# Generated by Django 5.2.11 on 2026-04-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_otpverification_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='is_validated',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='max_attempts',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='user',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
