# Generated by Django 5.2.3 on 2025-08-27 01:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du groupe')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_reset', models.DateTimeField(blank=True, null=True)),
                ('code_invitation', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invitation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="Code d'invitation")),
                ('montant_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant de base')),
                ('montant_fixe_gagnant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant fixe pour les gagnants')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_administres_ec', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'db_table': 'epargnecredit_group',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actionlogs_ec', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_logs_ec', to='epargnecredit.group')),
            ],
            options={
                'db_table': 'epargnecredit_actionlog',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('exit_liste', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='epargnecredit.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupmembers_ec', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'epargnecredit_groupmember',
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='membres_ec',
            field=models.ManyToManyField(related_name='groupes_ec', through='epargnecredit.GroupMember', to=settings.AUTH_USER_MODEL, verbose_name='Membres'),
        ),
        migrations.AddField(
            model_name='group',
            name='prochain_gagnant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_prochain_gagnant_ec', to='epargnecredit.groupmember', verbose_name='Prochain gagnant à exclure'),
        ),
        migrations.CreateModel(
            name='EpargneCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('VALIDE', 'Validé'), ('EN_ATTENTE', 'En attente'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations_ec', to='epargnecredit.groupmember')),
            ],
            options={
                'db_table': 'epargnecredit_cotisation',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('RESET_CYCLE', 'Réinitialisation du cycle'), ('AUTRE', 'Autre action')], max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_actions_ec', to='epargnecredit.group')),
            ],
            options={
                'db_table': 'epargnecredit_historiqueaction',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_ec', to='epargnecredit.group')),
            ],
            options={
                'db_table': 'epargnecredit_invitation',
            },
        ),
        migrations.CreateModel(
            name='PaiementGagnant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('SUCCES', 'Succès'), ('ECHEC', 'Échec')], max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('gagnant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_reçus_ec', to='epargnecredit.groupmember')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_ec', to='epargnecredit.group')),
            ],
            options={
                'verbose_name': 'Paiement gagnant',
                'verbose_name_plural': 'Paiements des gagnants',
                'db_table': 'epargnecredit_paiementgagnant',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Tirage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tirage', models.DateField(auto_now_add=True, verbose_name='Date du tirage')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant du tirage')),
                ('gagnant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tirages_gagnes_ec', to='epargnecredit.groupmember', verbose_name='Membre gagnant')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tirages_ec', to='epargnecredit.group', verbose_name='Groupe')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tirages_participes_ec', to='epargnecredit.groupmember', verbose_name='Membre tiré')),
            ],
            options={
                'db_table': 'epargnecredit_tirage',
            },
        ),
        migrations.CreateModel(
            name='TirageHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_tirage', models.DateTimeField(auto_now_add=True)),
                ('gagnant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epargnecredit.groupmember', verbose_name='Gagnant')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tirages_historiques_ec', to='epargnecredit.group')),
            ],
            options={
                'db_table': 'epargnecredit_tirage_historique',
            },
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant net du versement (hors frais).', max_digits=12)),
                ('frais', models.DecimalField(decimal_places=2, default=0, help_text='Frais appliqués sur le paiement.', max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('methode', models.CharField(choices=[('PAYDUNYA', 'PayDunya'), ('CASH', 'Caisse')], default='PAYDUNYA', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements_ec', to='epargnecredit.groupmember')),
            ],
            options={
                'db_table': 'epargnecredit_versement',
            },
        ),
    ]
