# Generated by Django 5.2.11 on 2026-04-04 13:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_reset', models.DateTimeField(blank=True, null=True)),
                ('code_invitation', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invitation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('montant_base', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('montant_fixe_gagnant', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('is_remboursement', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_administres_ec', to=settings.AUTH_USER_MODEL)),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remboursement_children', to='epargnecredit.group')),
            ],
            options={
                'db_table': 'epargnecredit_group',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actionlogs_ec', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_logs_ec', to='epargnecredit.group')),
            ],
            options={
                'db_table': 'epargnecredit_actionlog',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('montant', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('actif', models.BooleanField(default=True)),
                ('exit_liste', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_ec', to='epargnecredit.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupmembers_ec', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'epargnecredit_groupmember',
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='membres_ec',
            field=models.ManyToManyField(related_name='groupes_ec', through='epargnecredit.GroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='prochain_gagnant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_prochain_gagnant_ec', to='epargnecredit.groupmember'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_ec', to='epargnecredit.group')),
            ],
            options={
                'db_table': 'epargnecredit_invitation',
            },
        ),
        migrations.CreateModel(
            name='PretDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('interet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nb_mois', models.PositiveIntegerField()),
                ('debut_remboursement', models.DateField()),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Refusé')], default='PENDING', max_length=10)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prets_decides_ec', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_pret_ec', to='epargnecredit.groupmember')),
            ],
            options={
                'db_table': 'epargnecredit_pretdemande',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PretRemboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('methode', models.CharField(default='CAISSE', max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='epargnecredit.pretdemande')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'epargnecredit_pret_remboursement',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('frais', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('methode', models.CharField(default='CAISSE', max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20)),
                ('numero_recu', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements_ec', to='epargnecredit.groupmember')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements_valides_ec', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'epargnecredit_versement',
                'ordering': ['-date_creation'],
            },
        ),
    ]
