# Generated by Django 5.2.11 on 2026-04-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epargnecredit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='versement',
            name='preuve',
            field=models.ImageField(blank=True, null=True, upload_to='preuves/epargnecredit/'),
        ),
        migrations.AlterField(
            model_name='versement',
            name='methode',
            field=models.CharField(choices=[('CAISSE', 'Caisse'), ('WAVE', 'Wave'), ('OM', 'Orange Money')], default='CAISSE', max_length=20),
        ),
    ]
