# Generated by Django 5.2.11 on 2026-03-07 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epargnecredit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PretRemboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('methode', models.CharField(default='CAISSE', max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='VALIDE', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='epargnecredit.pretdemande')),
            ],
            options={
                'db_table': 'epargnecredit_pret_remboursement',
                'ordering': ['-date_creation'],
            },
        ),
    ]
