# Generated by Django 5.2.3 on 2025-08-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epargnecredit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tirage',
            name='gagnant',
        ),
        migrations.RemoveField(
            model_name='tirage',
            name='group',
        ),
        migrations.RemoveField(
            model_name='tirage',
            name='membre',
        ),
        migrations.RemoveField(
            model_name='tiragehistorique',
            name='gagnant',
        ),
        migrations.RemoveField(
            model_name='tiragehistorique',
            name='group',
        ),
        migrations.DeleteModel(
            name='PaiementGagnant',
        ),
        migrations.DeleteModel(
            name='Tirage',
        ),
        migrations.DeleteModel(
            name='TirageHistorique',
        ),
    ]
