# Generated by Django 5.2.11 on 2026-04-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epargnecredit', '0002_versement_preuve_alter_versement_methode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versement',
            name='preuve',
        ),
        migrations.AlterField(
            model_name='versement',
            name='methode',
            field=models.CharField(default='CAISSE', max_length=20),
        ),
    ]
