# Generated by Django 5.2.11 on 2026-03-11 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epargnecredit', '0002_pretremboursement'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='versement',
            name='epargnecred_statut_76ed0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='versement',
            name='epargnecred_methode_b56dd6_idx',
        ),
        migrations.RemoveIndex(
            model_name='versement',
            name='epargnecred_numero__f81ac5_idx',
        ),
    ]
