# Generated by Django 5.2.3 on 2025-08-31 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epargnecredit', '0002_remove_tirage_gagnant_remove_tirage_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='expire_at',
        ),
    ]
