# Generated by Django 5.2.3 on 2025-09-01 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epargnecredit', '0003_remove_invitation_expire_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PretDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('interet', models.DecimalField(decimal_places=2, help_text='Pourcentage annuel simple, ex. 5 pour 5%', max_digits=5)),
                ('nb_mois', models.PositiveIntegerField()),
                ('debut_remboursement', models.DateField()),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Refusé')], default='PENDING', max_length=10)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prets_decides_ec', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_pret_ec', to='epargnecredit.groupmember')),
            ],
            options={
                'db_table': 'epargnecredit_pretdemande',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('statut', 'PENDING')), fields=('member',), name='uniq_pending_pret_par_membre_ec')],
            },
        ),
    ]
