# Generated by Django 5.2.11 on 2026-03-12 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epargnecredit', '0003_remove_versement_epargnecred_statut_76ed0d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pretdemande',
            name='uniq_pending_pret_par_membre_ec',
        ),
        migrations.RemoveField(
            model_name='pretremboursement',
            name='statut',
        ),
    ]
