# Generated by Django 5.2.3 on 2025-09-02 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epargnecredit', '0004_pretdemande'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_remboursement',
            field=models.BooleanField(default=False, help_text='Coché pour un groupe de remboursement'),
        ),
        migrations.AddField(
            model_name='group',
            name='parent_group',
            field=models.ForeignKey(blank=True, help_text='Si groupe de remboursement, lien vers le groupe parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remboursement_children', to='epargnecredit.group'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['is_remboursement'], name='epargnecred_is_remb_c58936_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['admin'], name='epargnecred_admin_i_175a00_idx'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('is_remboursement', True)), fields=('parent_group', 'is_remboursement'), name='unique_one_remboursement_per_parent_ec'),
        ),
    ]
