# Generated by Django 5.2.3 on 2026-02-24 00:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epargnecredit', '0005_group_is_remboursement_group_parent_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epargnecredit',
            name='member',
        ),
        migrations.RemoveField(
            model_name='historiqueaction',
            name='group',
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterModelOptions(
            name='versement',
            options={'ordering': ['-date_creation']},
        ),
        migrations.RemoveConstraint(
            model_name='group',
            name='unique_one_remboursement_per_parent_ec',
        ),
        migrations.RenameField(
            model_name='versement',
            old_name='date',
            new_name='date_creation',
        ),
        migrations.AddField(
            model_name='versement',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='versement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='versement',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements_valides_ec', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_administres_ec', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_remboursement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='membres_ec',
            field=models.ManyToManyField(related_name='groupes_ec', through='epargnecredit.GroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='montant_base',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='group',
            name='montant_fixe_gagnant',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remboursement_children', to='epargnecredit.group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='prochain_gagnant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_prochain_gagnant_ec', to='epargnecredit.groupmember'),
        ),
        migrations.AlterField(
            model_name='group',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_ec', to='epargnecredit.group'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='montant',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pretdemande',
            name='interet',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='versement',
            name='frais',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='versement',
            name='methode',
            field=models.CharField(default='CAISSE', max_length=20),
        ),
        migrations.AlterField(
            model_name='versement',
            name='montant',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['statut'], name='epargnecred_statut_76ed0d_idx'),
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['methode'], name='epargnecred_methode_b56dd6_idx'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('is_remboursement', True)), fields=('parent_group',), name='unique_one_remboursement_per_parent_ec'),
        ),
        migrations.DeleteModel(
            name='EpargneCredit',
        ),
        migrations.DeleteModel(
            name='HistoriqueAction',
        ),
    ]
