# Generated by Django 5.2.3 on 2026-02-24 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epargnecredit', '0006_remove_epargnecredit_member_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='versement',
            name='numero_recu',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['numero_recu'], name='epargnecred_numero__f81ac5_idx'),
        ),
    ]
